### ISSUE TITLE
remove page formatting from https://pbx-group-security.com/roles/why-photobox/

### ISSUE THREAD

**Issue by JemmaDSmith** [photobox/pbx-group-security#131]
https://pbx-group-security.com/roles/why-photobox/ is inheriting roles layout

**Comment by fzipi** [comment]
@JemmaDSmith The new url is https://pbx-group-security.com/page/why-photobox/.

Every file you put into the 'content' directory willl be listed with the same url prefix of that directory, excepting blog posts.

For example, if you move a file to '/content/page', will be published as '/page/<pagename>'. For blogs is a little bit different, but that happens because we configured to use dates in the link.

So I ended updating the link from the "features" to point to this new url in commit 2f71d1a . Don't know yet why *both* urls are working....
